import popular1 from "../../../assets/images/main/popular1.jpg";
import popular2 from "../../../assets/images/main/popular2.jpg";
import popular3 from "../../../assets/images/main/popular3.jpg";
import popular4 from "../../../assets/images/main/popular4.jpg";

export const wallpapers = [
  { title: "Дизайнерские обои", id: 1 },
  { title: "Виниловые обои", id: 2 },
  { title: "Фирменные обои", id: 3 },
];

export const catalog = [
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 700 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 250 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 100 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 400 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 750 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 1 900 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 2 200 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 1 950 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
  {
    img: popular3,
    title: "Floraison",
    desc: "от 2 100 ₽ / м2",
    additionally: "Артикул 44032",
    link: "/product",
  },
  {
    img: popular2,
    title: "Floraison",
    desc: "от 2 800 ₽ / м2",
    additionally: "Артикул 5432",
    link: "/product",
  },
  {
    img: popular1,
    title: "Floraison",
    desc: "от 1 1650 ₽ / м2",
    additionally: "Артикул 11052",
    link: "/product",
  },
  {
    img: popular4,
    title: "Floraison",
    desc: "от 2 000 ₽ / м2",
    additionally: "Артикул 7878",
    link: "/product",
  },
];
